export { Game, GameRuleError, type GameSnapshot } from './game.js';
export { DEFAULT_CONFIG, type GameConfig } from './config.js';
export {
  BUILDING_CATALOG,
  getBuildingDef,
  isKnownBuildingId,
  sanitizeBuildingState,
  totalWallDefenseFromBuildings,
  totalWatchBonusFromBuildings,
  totalWaterPerDawnFromBuildings,
  totalHordeDeterrenceFromBuildings,
  totalCasualtyReductionFromBuildings,
  type BuildingCost,
  type BuildingDef,
  type BuildingId,
  type BuildingState,
} from './buildings.js';
export {
  ITEM_CATALOG,
  getItemDef,
  isKnownItemId,
  sanitizeItemStock,
  stockCoversCost,
  pickDroppableItem,
  foodItemsByAbundance,
  type ItemCategory,
  type ItemRarity,
  type ItemDef,
  type ItemId,
  type ItemStock,
  type ItemCost,
} from './items.js';
export {
  NIGHT_THREAT_CATALOG,
  DEFAULT_ZOMBIE_CONFIG,
  NO_THREATS,
  computeNightThreats,
  hasThreats,
  bruteWallPierce,
  screamerHordeBonus,
  type NightThreatKind,
  type NightThreatCounts,
  type NightThreatDef,
  type ZombieConfig,
} from './zombies.js';
export {
  ACHIEVEMENT_CATALOG,
  getAchievementDef,
  isKnownAchievementId,
  buildAchievements,
  scavengeAchievements,
  nightAchievements,
  type AchievementId,
  type AchievementDef,
} from './achievements.js';
export { buildEpitaph, type EpitaphInput } from './epitaph.js';
export {
  RECIPE_CATALOG,
  CRAFTING_BUILDING,
  getRecipeDef,
  isKnownRecipeId,
  recipeBlocker,
  totalRations,
  type RecipeId,
  type RecipeDef,
  type RecipeGroup,
  type CraftInputs,
  type CraftOutputs,
  type CraftResources,
  type CraftBlocker,
} from './crafting.js';
export {
  buildEndgameCard,
  survivorTitle,
  difficultyLabel,
  type CardRole,
  type EndgameCardEntry,
  type EndgameCardInput,
  type EndgameCardSummary,
} from './endgame-card.js';
export {
  ELECTION_INTERVAL_DAYS,
  emptyGovernance,
  sanitizeGovernance,
  strictMajority,
  canOpenElection,
  openElection,
  castMayorVote,
  mayorTally,
  closeElection,
  isMayor,
  curfewActive,
  decreeCurfew,
  pruneMayor,
  openMotionAgainst,
  openExileMotion,
  exileTally,
  castExileVote,
  dropMotion,
  cancelMotionsAgainst,
  type GovernanceState,
  type Mayor,
  type MayorElection,
  type Curfew,
  type ExileMotion,
  type ExileStatus,
  type ExileTally,
  type MayorTallyLine,
} from './governance.js';
export type {
  AttackWave,
  Citizen,
  Death,
  DeathSource,
  DeathsBySource,
  DefenseBreakdown,
  SabotageReport,
  GameOutcome,
  GameStatus,
  Location,
  NightReport,
  Phase,
  ResourceBank,
  ResourceKind,
  ZoneEventKind,
  ZoneEventSnapshot,
  DesertZoneSnapshot,
  DesertSnapshot,
} from './types.js';
